# Generated by Django 4.2.1 on 2023-10-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=4, unique=True)),
                ('building_name', models.CharField(max_length=100, unique=True)),
                ('floor', models.CharField(max_length=2)),
                ('room', models.IntegerField()),
            ],
        ),
    ]
