# Generated by Django 4.2.6 on 2023-10-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('UserName', models.CharField(max_length=500)),
                ('userEmail', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
