# Generated by Django 4.2.5 on 2023-10-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='photoFileName',
        ),
        migrations.AddField(
            model_name='user',
            name='Interest',
            field=models.CharField(default='Your Interest', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='Major',
            field=models.CharField(default='Your Major', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
