# Generated by Django 4.2.1 on 2023-10-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlocation',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='classlocation',
            name='room',
        ),
    ]
