# Generated by Django 4.2.5 on 2023-10-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_profile_pic_user_photofilename_user_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='securityAnswer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='securityQuestion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
