# Generated by Django 4.2.1 on 2023-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_classlocation_floor_remove_classlocation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlocation',
            name='acronym',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
