# Generated by Django 4.2.1 on 2023-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classlocation_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('UserName', models.CharField(max_length=500)),
                ('UserEmail', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500, null=True)),
                ('Major', models.CharField(default='Your Major', max_length=500)),
                ('Interest', models.CharField(default='Your Interest', max_length=1000)),
            ],
        ),
    ]
