# Generated by Django 4.2.1 on 2023-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
